POST https://studying-nodejs.onrender.com/videos
Content-Type: application/json

{
  "title": "Video node",
  "description": "Este é o vídeo 01",
  "duration": 180
}

###

GET https://studying-nodejs.onrender.com/videos

###

PUT https://studying-nodejs.onrender.com/videos/5e0d1551-4963-48a4-a674-2da6c00377da
Content-Type: application/json

{
  "title": "Video aeeee",
  "description": "Este é o primeiro vídeo",
  "duration": 180
}
###

DELETE https://studying-nodejs.onrender.com/videos/5e0d1551-4963-48a4-a674-2da6c00377da