POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Video node",
  "description": "Este é o vídeo 01",
  "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/2ce493a8-2dc7-49ba-801e-8129e092f90d
Content-Type: application/json

{
  "title": "Video 02",
  "description": "Este é o primeiro vídeo",
  "duration": 180
}
###

DELETE http://localhost:3333/videos/2ce493a8-2dc7-49ba-801e-8129e092f90d